jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [api-service, auth-service, scrapper-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image for ${{ matrix.service }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/docker/Dockerfile
          push: false  # Construye la imagen localmente
          tags: ${{ matrix.service }}:test

      - name: Run container for ${{ matrix.service }}
        run: |
          docker run -d --rm --name test-container-${{ matrix.service }} -p 3000:3000 ${{ matrix.service }}:test
          sleep 5  # Tiempo para inicializar el contenedor

      - name: Run Jest tests for ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: |
          npm install
          npm test

      - name: Stop and remove container
        if: always()
        run: docker stop test-container-${{ matrix.service }}
