name: Build and Deploy with Docker Compose v2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [api-service, auth-service, scrapper-service] # Asumiendo que tienes estos servicios

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies for ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: npm install

      - name: Start server for ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: |
          npm start &
          sleep 5  # Dar tiempo al servidor para iniciar

      - name: Run tests for ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test  # Solo se ejecutará si el job "test" tiene éxito

    strategy:
      matrix:
        service: [api-service, auth-service, scrapper-service] # Asumiendo que tienes estos servicios

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Debug secrets
        run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} DOCKER_TOKEN=${{ secrets.DOCKER_TOKEN }}"

      - name: Log in to Docker Hub using token
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image for ${{ matrix.service }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest, ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
