name: Build, Test, and Deploy with Docker Compose v2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [api-service, auth-service, scrapper-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build Docker image for ${{ matrix.service }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/docker/Dockerfile
          push: false
          tags: ${{ matrix.service }}:test

      - name: Run container for ${{ matrix.service }}
        run: |
          docker run -d --rm --name test-container-${{ matrix.service }} -P ${{ matrix.service }}:test
          sleep 5

      - name: Run tests against container
        working-directory: ./${{ matrix.service }}
        run: |
          npm install
          npm test

      - name: Capture container logs on failure
        if: failure()
        run: docker logs test-container-${{ matrix.service }}

      - name: Stop and remove container
        if: always()
        run: docker stop test-container-${{ matrix.service }}
