name: Build Docker Images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-service, auth-service]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Debug secrets
      run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} DOCKER_TOKEN=${{ secrets.DOCKER_TOKEN }}"
    - name: Log in to Docker Hub using token
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Se mantiene el nombre de usuario
        password: ${{ secrets.DOCKER_TOKEN }}     # Usamos el token de acceso

    - name: Build and push Docker image for ${{ matrix.service }}
      uses: docker/build-push-action@v2
      with:
        context: ./${{ matrix.service }}/src
        file: ./${{ matrix.service }}/Docker/Dockerfile
        push: true
        tags: username/${{ matrix.service }}:latest, username/${{ matrix.service }}:${{ github.sha }}
